spring.application.name=paramx
spring.datasource.url=jdbc:mysql://paramxdb.cwzkbtsndtvj.eu-west-2.rds.amazonaws.com:3306/paramx
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

