name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Update env profile
        run: sed -i 's#spring.profiles.active=dev#spring.profiles.active=prod#g' "src/main/resources/application.properties"

      - name: Update db url
        run: sed -i 's#<dbUrl>#${{ secrets.DB_URL }}#g' "src/main/resources/application-prod.properties"

      - name: Update db username
        run: sed -i 's/<dbUsername>/${{ secrets.DB_USERNAME }}/' src/main/resources/application-prod.properties

      - name: Update db password
        run: sed -i 's/<dbPassword>/${{ secrets.DB_PASSWORD }}/' src/main/resources/application-prod.properties

      - uses: actions/setup-python@v3

      - uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset